// APP Icons Strings

const ageIconImage = "assets/icons_images/age_icon.png";
const areaIconImage = "assets/icons_images/area_icon.png";
const bmiIconImage = "assets/icons_images/bmi_icon.png";
const basicCalIconImage = "assets/icons_images/basic_cal.png";
const currencyIconImage = "assets/icons_images/currency_icon.png";
const dataIconImage = "assets/icons_images/data-converter.png";
const dateIconImage = "assets/icons_images/calender.png";
const discountIconImage = "assets/icons_images/discount.png";
const gstIconImage = "assets/icons_images/gst_icon.png";
const investmentIconImage = "assets/icons_images/investment.png";
const lengthIconImage = "assets/icons_images/length.png";
const loanIconImage = "assets/icons_images/loan.png";
const massIconImage = "assets/icons_images/mass.png";
const numericSystemIconImage = "assets/icons_images/numeric_system.png";
const scientificCalIconImage = "assets/icons_images/scientific_cal_icon.png";
const speedIconImage = "assets/icons_images/speed_icon.png";
const temperatureIconImage = "assets/icons_images/temperatures.png";
const timeIconImage = "assets/icons_images/time.png";
const volumeIconImage = "assets/icons_images/volume.png";
